[package]
name = "cuda_rand"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "cuda_rand"
path = "src/lib.rs"

[build-dependencies]
bindgen = "^0.38"

[dependencies]
cuda = "^0.3"
